#pragma once
#ifndef CONTROLLER_H
#define CONTROLLER_H

#include <vector>
#include <iostream>
#include <cmath>
#include "eigen-3.4.1/Eigen/Dense"

struct Remebered_Data
{
	float point_number;
	float Pv;
	float Sp;
	float Co;
	float Pv_slope, Co_slope;
	float kc;
};


class Controller
{
public:
	// Transfer Function generated by controller, for prediction of a1 b1 and c1 for controller action.
	// Used to change the control veribles dynamicly
	float Sa1, Sb1, Sc1;

	float prev_Pv = 0, prev_Co = 0;

	//standard PID stuff which all controllers ussaly contain.
	float Sp = 0, Co = 0, Pv = 0, Mo = 0;
	float Gain = 1, TI = 0, TD = 0;
	float prev_error = 0, oldintergrated = 0, prev_Sp = 0;
	float low_limit = 0, high_limit = 100;
	bool direct_acting = false, AUTO = true, smart = false;

	// --- RLS Variables ---
	Eigen::Vector3d theta; // [a1, b1, c1 (Bias)]
	Eigen::Matrix3d P;
	double lambda = 0.98;  // Forgetting factor
	bool rls_initialized = false;
	float macroPv=0, macroCo=0, macroPvold = 0;
	float effctive_factor = 0.1;
	bool enable_RLS = true;

	// --- MPC Variables ---
	float MPCCo = 0.0f;           // MPC level
	float MPCCo_limit = 100.0f;      // Max % the MPC can contribute
	float excitation_deadzone = 0.02f; // Minimum slope required to learn
	float smoothed_MPCCo = 0.0f;
	float MPCCo_smoothing_alpha = 0.005f; //smoother for MPC control output. less then 0 = more smooth.
	float errorsaved = 0;
	float predictionsaved = 0;
	float timer = 0;
	float prev_delta_slope = 0.0f;
	float prev_macroCo = 50.0f;

	float saved_slope;

	float mpc_blanking_timer = 0.0f;

	float timetorun = 0;

	Controller() // controllers contructor.
	{
		// Initialize 3x3 Covariance Matrix
		P << 1000.0, 0.0, 0.0,
			0.0, 1000.0, 0.0,
			0.0, 0.0, 1000.0;

		// Baseline guess: Damping, Small Gain, 0 Bias
		theta << 0.5, 0.005, -0.011;
		Sa1 = 0.5;
		Sb1 = 0.005;
		Sc1 = -0.01;
	}
	
	void Update(double Timestep)
	{
		float savedtime = glfwGetTime();
		if (AUTO)//check if controller is in automatic mode.
		{
			float error, kc = Gain, ki = 1 / TI, kd = TD;
			if (prev_Sp != Sp)
			{
				//Mo = Co;
				prev_Sp = Sp;
				//oldintergrated = Mo;
			}
			if (TI == 0)
			{
				ki = 0;
			}
			if (direct_acting)
			{
				error = (Pv - Sp);
			}
			else
			{
				error = (Sp - Pv);
			}



			float derivitive = (kc * kd * ((error - prev_error) / ((Timestep/60)-0)));
			float intergrated = oldintergrated + (kc * ki * error * (Timestep / 60));

			Co = ((kc * error) + (intergrated)+(derivitive)); // this is the equation for the gain only component of the controller.


			//The "Smart" part
			if (smart)
			{
				float Pv_slope = ((Pv - prev_Pv) / Timestep);
				mpc_blanking_timer += Timestep;
				timer += Timestep;
				// Calculate new MPC action
				if (timer > 3)
				{
					timer = 0;
					MPCCo = Calculate_MPC(Pv, Sp, Pv_slope);
				}
				

				smoothed_MPCCo = EMA_Filter(MPCCo, smoothed_MPCCo, MPCCo_smoothing_alpha);


				Co = Co + smoothed_MPCCo; // apply output to Co

				// If the slope is larger than ~0 or nothing, the plane is maneuvering or rejecting a distrubence == learn

				saved_slope = abs((Co - prev_Co) / Timestep);
				bool is_excited = (saved_slope > excitation_deadzone)&&(Co < 90 || Co > 10);

				if (is_excited && mpc_blanking_timer > 6 && enable_RLS)
				{


					// Update Plant Parameters
					RLS(Pv_slope, macroPvold);

						if (theta[0] < 0)
						{
						theta[0] = 0.3;
						}
						if (theta[1] < 0.001)
						{
							theta[1] = 0.001;
						}
						if (theta[1] > 0.011)
						{
							theta[1] = 0.011;
						}
						if (theta[2] > 0)
						{
							theta[2] = -0.001;
						}
						if (theta[0] > 0.6)
						{
							theta[0] = 0.6;
						}
				}
				if (mpc_blanking_timer > 6 && enable_RLS)
				{
					Sa1 = EMA_Filter(theta[0], Sa1, effctive_factor);
					Sb1 = EMA_Filter(theta[1], Sb1, effctive_factor);
					Sc1 = EMA_Filter(theta[2], Sc1, effctive_factor);
					macroPvold = Pv_slope;
					macroCo = prev_Co - 50;
					mpc_blanking_timer = 0;
				}

			}
			else
			{
				// Slowly decay the trim back to 0 when smart is disabled.
				smoothed_MPCCo = EMA_Filter(0.0f, smoothed_MPCCo, 0.00001);
				Co = Co + smoothed_MPCCo; // apply output to Co
			}

			// Anti-Windup
			if (Co > high_limit)
			{
				Co = high_limit;
				// Back calculate the integral to exactly what is needed to hit 100 Co
				intergrated = high_limit - (kc * error) - derivitive - smoothed_MPCCo;
			}
			else if (Co < low_limit)
			{
				Co = low_limit;
				// Back calculate the integral to exactly what is needed to hit 0 Co
				intergrated = low_limit - (kc * error) - derivitive - smoothed_MPCCo;
			}

			oldintergrated = intergrated;
			prev_error = error;
			prev_Pv = Pv;
			prev_Co = Co;

		}
		else
		{
			Sp = Pv;
		}
		timetorun = glfwGetTime() - savedtime;
	}

private:
	float EMA_Filter(float current_val, float previous_val, float alpha)
	{
		return (alpha * current_val) + ((1.0f - alpha) * previous_val);
	}

	void RLS(float current_Pv_slope,float prev_pv_slope)
	{
		// Regression Vector includes a constant '1.0' to map the C1 bias
		float ddelayed_prev_Co= prev_Co - 50; // -50 since the 0 pitch change is at 50%
		Eigen::Vector3d phi(-prev_pv_slope, macroCo, 1.0f);

		double denom = lambda + (phi.transpose() * P * phi)(0, 0);
		Eigen::Vector3d K = (P * phi) / denom;

		double prediction = (phi.transpose() * theta)(0, 0);
		double rls_error = current_Pv_slope - prediction;
		errorsaved = rls_error;
		predictionsaved = prediction;


		theta += K * rls_error;
	

		P = (P - K * phi.transpose() * P)	/ lambda;
	}

	float Calculate_MPC(float current_Pv, float target_Sp, float current_Pv_slope)
	{
		double a1 = Sa1;
		double b1 = Sb1;
		double c1 = Sc1;

		// Prevent division by zero if rls gives small b
		if (std::abs(b1) < 0.001) { b1 = 0.001; }
		if (a1 > 0.6) // cap a1 value so MPC does not explode
		{
			a1 = 0.6;
		}
		// Calculate Target Vertical Speed to reach Setpoint
		float horizon_time = 2.0f;
		float v_target = (target_Sp - current_Pv) / horizon_time;

		// --- EXTENDED PREDICTION HORIZON ---
		int N_steps = 15; // Look 15 steps (30 seconds) into the future
		double alpha = a1;

		// Calculate the geometric series multiplier: 1 + alpha + alpha^2 + ... + alpha^(N-1)
		double S = 0.0;
		for (int i = 0; i < N_steps; i++)
		{
			S += std::pow(alpha, i);
		}

		// Multi-Step Free Response 
		// Anticipates the decay of the current trajectory N steps from now based on provided model
		double free_response_N = (std::pow(alpha, N_steps) * current_Pv_slope) + (S * c1);

		// Multi-Step Control Multiplier 
		// Accumulates the total effect of the control input over the N steps
		double B_N = S * b1;

		// --- MPC Cost Function Weights ---
		double Q = 2.5;   // Tracking penalty

		// Note: Because B_N accumulates over N steps, its value is much larger than b1.
		double R = 0.005;

		double previous_u = MPCCo;

		// What will the vertical speed be N steps from now if we don't move the Co?
		double predicted_V = free_response_N + (B_N * previous_u);

		// Where will the plane's Altitude (Pv) be N steps from now?
		// use trapezoidal integration (average speed * time) to project the physical position.
		double time_horizon_seconds = N_steps * 3.0;
		double average_V = (current_Pv_slope + predicted_V) / 2.0;
		double predicted_Pv = current_Pv + (average_V * time_horizon_seconds);

		// What will the outer loop command be when we reach that future altitude?
		// If predicted_Pv overshoots target_Sp, future_v_target automatically goes negative
		double outer_loop_time = 9.0f;
		double future_v_target = (target_Sp - predicted_Pv) / outer_loop_time;

		// Calculate the optimal change in control effort to hit the future target
		double projected_error = future_v_target - predicted_V;
		double delta_u = (Q * B_N * projected_error) / ((Q * B_N * B_N) + R);

		double raw_MPCCo = previous_u + delta_u;

		// Clamp to limits if applied.
		if (raw_MPCCo > MPCCo_limit) return MPCCo_limit;
		if (raw_MPCCo < -MPCCo_limit) return -MPCCo_limit;

		return static_cast<float>(raw_MPCCo);
	}

};

#endif