#pragma once
#ifndef CONTROLLER_H
#define CONTROLLER_H

#include <vector>
#include <iostream>

struct Remebered_Data
{
	float point_number;
	float Pv;
	float Sp;
	float Co;
	float Pv_slope, Co_slope;
	float kc;
};


class Controller
{
public:
	// Transfer Function generated by controller, for prediction of gain t1 and td for controller action.
	// Used to change the control veribles dynamicly
	float guessed_Kp, guessed_KpT1, guessed_KpTd;

	float max_devation = 0.05;
	float max_points = 100, actualpoint_count = 0;
	float prev_Pv = 0, prev_Co = 0;
	float counter = 0;

	float Sp = 50, Co = 0, Pv = 0, Mo = 0;
	float Gain = 1, TI = 0, TD = 0;
	float prev_error = 0, oldintergrated = 0, prev_Sp = 0;
	float timepoint; //stores the amount of points remembered.
	std::vector<Remebered_Data> points;
	bool direct_acting = false, AUTO = true;
	Controller() // controllers contructor.
	{
		
		points.resize(max_points); //reserves memory for 100 points into controller for memory.
	}
	
	void Update(double Timestep)
	{
		if (AUTO)//check if controller is in automatic mode.
		{
			float error, kc = Gain, ki = 1 / TI, kd = TD;
			if (prev_Sp != Sp)
			{
				Mo = Co;
				prev_Sp = Sp;
			}
			if (TI == 0)
			{
				ki = 0;
			}
			if (direct_acting)
			{
				error = (Pv - Sp);
			}
			else
			{
				error = (Sp - Pv);
			}



			float derivitive = (kc * kd * ((error - prev_error) / ((Timestep/60)-0)));
			float intergrated = oldintergrated + (kc * ki * error * (Timestep / 60));

			Co = ((kc * error) + (intergrated) + (derivitive)); // this is the equation for the gain only component of the controller.

			if (counter > 1)// update stored data every set amount of updates.
			{
				counter = 0;
				getdata(Timestep);
			}
			else
			{
				counter += Timestep;
			}

			oldintergrated = intergrated;

			prev_error = error;
			prev_Pv = Pv;
			prev_Co = Co;

			if (Co > 100)
			{
				Co = 100;
			}
			if (Co < 0)
			{
				Co = 0;
			}
		}
		else
		{
			Sp = Pv;
		}
	}

private:
	//Gets data at set times and stores it for later use.
	void getdata(float timestep)
	{
		points[actualpoint_count].Pv = Pv;
		points[actualpoint_count].Sp = Sp;
		points[actualpoint_count].Co = Co;
		points[actualpoint_count].Pv_slope = ((Pv - prev_Pv / timestep));
		points[actualpoint_count].Co_slope = ((Co - prev_Co / timestep));
		points[actualpoint_count].kc = Gain;
		points[actualpoint_count].point_number = actualpoint_count;

		actualpoint_count++;
		if (max_points == actualpoint_count)
		{
			check_Transferfunction();
			actualpoint_count = 0;
		}
	}
	//updates the transferfunction and 
	void check_Transferfunction()
	{
		
		for (auto point : points) // checks each point in points vector
		{
			float total_slope_Pv = 0;
			float total_slope_Co = 0;
			if (point.point_number >= 10 && point.point_number <= max_points - 10)
			{
				for (int i = 0; i < 20; i++)
				{
					if (i <= 10)
					{
						total_slope_Pv += points[point.point_number - i].Pv_slope;
					}
					if (i > 10)
					{
						total_slope_Pv += points[point.point_number + (i-10)].Pv_slope;
					}
					if (i == 19)
					{
						total_slope_Pv += points[point.point_number + 10].Pv_slope;
					}
					if (i <= 10)
					{
						total_slope_Co += points[point.point_number - i].Co_slope;
					}
					if (i > 10)
					{
						total_slope_Co += points[point.point_number + (i - 10)].Co_slope;
					}
					if (i == 19)
					{
						total_slope_Co += points[point.point_number + 10].Co_slope;
					}
				}
				if (total_slope_Pv < max_devation && total_slope_Pv > -max_devation)
				{
					if (total_slope_Co < max_devation && total_slope_Co > -max_devation)
					{
						guessed_Kp = point.Pv / point.Co;
					}
				}
			}
		}
	}
};

#endif